fairDataSociety/fairdrive-theapp

- .example.env.local
- src/components/Forms/LoginForm/LoginForm.tsx
- redirect to https://create.dev.fairdatasociety.org/#/register
> feat: create account redirect

- package.json
- src/api/files.ts
- src/api/pod.ts
- src/components/Buttons/UserDropdownToggle/UserDropdownToggle.tsx
- src/components/Layouts/MainLayout/MainLayout.tsx
- src/components/Modals/CreateFolderModal/CreateFolderModal.tsx
- src/components/Modals/CreatePodModal/CreatePodModal.tsx
- src/components/Modals/UploadFileModal/UploadFileModal.tsx
- src/components/NavigationBars/DriveSideBar/DriveSideBar.tsx
- src/components/NavigationBars/MainNavigationBar/MainNavigationBar.tsx
- src/components/Spinner/Spinner.tsx
- src/pages/drive/index.tsx
- src/pages/register/payment/index.tsx
- Fixes spinners
- Fixes API data models
> fix: spinners and data models working

- src/components/Buttons/MainSideBarItem/MainSideBarItem.tsx
- src/components/Cards/DriveCard/DriveCard.tsx
- src/components/Dropdowns/PodDropdown/PodDropdown.tsx
- src/components/Dropdowns/PodDropdown/PodDropdownMenu.tsx
- src/components/Dropdowns/PodDropdown/PodDropdownToggle.tsx
- src/components/Headers/MainHeader/MainHeader.tsx
- src/components/Inputs/SearchBar/SearchBar.tsx
- src/components/Layouts/MainLayout/MainLayout.tsx
- src/components/NavigationBars/DriveActionBar/DriveActionBarMobile.tsx
- src/components/NavigationBars/DriveActionBar/DriveActionHeaderMobile.tsx
- src/components/NavigationBars/DriveSideBar/DriveSideBar.tsx
- src/pages/drive/index.tsx
> fix: responsive fixes

- src/pages/explore/index.tsx
> fix: dapp links

- src/components/Forms/LoginForm/LoginForm.tsx
Fairos login checkbox removed.
> feat: remove fairos login

- src/data/explore-dapps.ts
> feat: add agenda app

- src/components/FilePreview/FilePreview.tsx
> feat: new consent viewer link

- src/components/Cards/SelectPodCard/SelectPodCard.tsx
- src/components/NavigationBars/DriveActionBar/DriveActionBar.tsx
- src/pages/drive/index.tsx
> feat: hide pod options when pod not selected

- src/api/files.ts
- src/api/pod.ts
- src/components/Cards/DriveCard/DriveCard.tsx
- src/components/FilePreview/FilePreview.tsx
- src/components/Modals/PreviewFileModal/PreviewFileModal.tsx
- src/components/Tables/DriveTableItem/DriveTableItem.tsx
- src/components/Views/DriveGridView/DriveGridView.tsx
- src/components/Views/DriveListView/DriveListView.tsx
- src/pages/drive/index.tsx
> fix: dates #280

- src/pages/overview/index.tsx
> fix: api link #282

- src/components/Cards/DriveCard/DriveCardIcon/DriveCardIcon.tsx
> fix: file extensions (#288)

- src/components/Cards/DriveCard/DriveCard.tsx
- src/components/Dropdowns/DriveItemDropdown/DriveItemDropdown.tsx
- src/components/Tables/DriveTableItem/DriveTableItem.tsx
- src/components/Views/DriveGridView/DriveGridView.tsx
- src/components/Views/DriveListView/DriveListView.tsx
- src/pages/drive/index.tsx
Only one file menu can be open at a time.
> feat: keep only one file menu open (#286)

- src/api/directory.ts
- src/components/DirectoryPath/DirectoryPath.tsx
- src/components/Dropdowns/PodDropdown/PodDropdownToggle.tsx
- src/pages/drive/index.tsx
> feat: directory path navigation

- package-lock.json
- package.json
Bumped `@svgr/webpack` as npm required
> fix: bumped high severity lib

- src/pages/_app.tsx
> fix: add title (#331)

- .github/workflows/docker.yml
- .github/workflows/node.js.yml
- .github/workflows/swarm.yml
> ci: switch to sepolia

- src/components/Footers/MainFooter/MainFooter.tsx
> fix: award logo

- src/components/Connect/Blossom/BlossomLogin.tsx
- src/components/Connect/Metamask/MetamaskConnect.tsx
- src/components/Forms/LoginForm/LoginForm.tsx
- src/components/NavigationBars/MainNavigationBar/UserDropdown/UserDropdown.tsx
- src/context/FdpStorageContext.tsx
- src/pages/index.tsx
- src/pages/invite/save-invite.tsx
- src/pages/overview/index.tsx
Storing invite to local storage.
> feat: store invite to local storage

- src/components/Modals/TopUpInviteModal/TopUpInviteModal.tsx
Changed min balance for invite top-up to `0.0101`
> fix: changed top-up balance

- .github/workflows/buildx.yml
- .github/workflows/swarm.yml
Since it was decided to test the application on the Swarm main network, the references to the Bee nodes should be changed.
> refactor: changed bee urls

- src/components/Connect/Metamask/MetamaskConnect.tsx
- src/components/Modals/MetamaskNotFoundModal/MetamaskNotFoundModal.tsx
Shows a dialog when Metamask extension is not available.
> fix: metamask not found (#368)

- .github/workflows/buildx.yml
Added env url for web2 build with BigBang api url
> refactor: added web2 env with BigBang api url

- src/components/Invite/Invite.tsx
- src/components/NavigationBars/MainNavigationBar/UserDropdown/UserDropdown.tsx
- src/utils/shortenString.ts
Added copy button for eth address of the account and newly created invite
> feat: copy button for eth address and invite

- .github/workflows/buildx.yml
Fixed url to the BigBang rules
> fix: fixed url to the bb rules

- src/components/Invites/Invites.module.scss
- src/components/Invites/Invites.tsx
- src/utils/invite.ts
Display the correct status of private invites
Close: https://github.com/fairDataSociety/fairdrive-theapp/issues/388
> feat: display the correct status of private invites

- package-lock.json
- package.json
- src/components/Buttons/MainSideBarItem/MainSideBarItem.tsx
- src/components/Layouts/MainLayout/MainLayout.tsx
- src/pages/_app.tsx
Added animations for page transitions.
> feat: animated page transitions (#392)

- src/components/Buttons/Button/Button.tsx
- src/pages/overview/index.tsx
Overview links fixed.
Closes #374
> fix: links in overview page (#374)

- src/components/Forms/LoginForm/LoginForm.tsx
- src/components/Layouts/AuthenticationLayout/AuthenticationLayout.tsx
Vertical space has been shrinked to fit the network selector.
> fix: login form spaceing

- src/components/Invite/Invite.tsx
- src/components/Invites/Invites.tsx
- src/components/Layouts/MainLayout/MainLayout.tsx
- src/utils/invite.ts
> Fix: invites storage (#380)

- src/components/Invites/Invites.tsx
> fix: invite length (#381)

- src/components/NavigationBars/DriveActionBar/DriveActionBar.tsx
- src/pages/overview/index.tsx
Removed titles to save space in pages.
Closes #417
> fix: remove titles (#417)

- src/components/Inputs/CustomCheckbox/CustomCheckbox.tsx
- src/components/Invite/Invite.tsx
> fix: checkboxes #390

- src/components/Modals/CreateFolderModal/CreateFolderModal.tsx
- src/components/Modals/CreatePodModal/CreatePodModal.tsx
- src/components/Modals/ImportFileModal/ImportFileModal.tsx
- src/components/Modals/ImportPodModal/ImportPodModal.tsx
- src/components/Modals/PasswordModal/PasswordModal.tsx
- src/components/Modals/UploadFileModal/UploadFileModal.tsx
> fix: button spinners (#405)

- src/components/Footers/MainFooter/MainFooter.tsx
- src/pages/linum-labs/index.tsx
- src/pages/my-data-operator/index.tsx
- src/pages/overview/index.tsx
- src/pages/overview/overview-card.tsx
- Removed some components from footer
- Added new overview cards
- Added new pages for LinumLabs and MyData Operator award
> feat: reorganize footer and add new pages (#420)

- .github/workflows/buildx.yml
- .github/workflows/swarm.yml
Fixes default network for development environment.
Closes #425
> ci: development config (#425)

- docs/USER-GUIDE.md
> chore: blossom login documentation

- package-lock.json
- package.json
- src/components/Dialogs/MetamaskMigrationDialog/MetamaskCreateAccount.tsx
- src/utils/ens.ts
Uses new fdp-storage with updated Sepolia RPC.
> feat: change sepolia rpc

- src/pages/linum-labs/index.tsx
- src/pages/my-data-operator/index.tsx
> fix: text on dark theme

- package-lock.json
- package.json
> feat: fdp-storage 0.11

- src/components/Connect/Metamask/MetamaskConnect.tsx
- src/components/Dialogs/MetamaskMigrationDialog/MetamaskUsernamePassword.tsx
- src/components/Forms/LoginForm/LoginForm.tsx
- src/components/NavigationBars/DriveSideBar/DriveSideBar.tsx
- src/context/FdpStorageContext.tsx
- src/utils/localStorage.ts
- src/utils/metamask.ts
Close https://github.com/fairDataSociety/fairdrive-theapp/issues/425
> fix: login via metamask with default network

- .github/workflows/variables.json
> fix: big bang urls

- src/locales/en-US.json
Changes title of modal window after login via Metamask.
> refactor: change passphrase title

- src/components/Modals/ShareFileModal/ShareFileModal.tsx
Fixed sharing behaviour
https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/99217cd2-900d-47f4-a349-9fbc648749f2
Close: https://github.com/fairDataSociety/fairdrive-theapp/issues/462
Close: https://github.com/fairDataSociety/fairdrive-theapp/issues/460
> fix: sharing behaviour

- src/utils/error.ts
Fixes error parsing
Closes #471
> fix: error parsing (#471)

- src/components/Dialogs/MetamaskMigrationDialog/MetamaskCreateAccount.tsx
Fixes how estimated min balance is displayed.
> fix: min balance display

- src/pages/drive/index.tsx
Fixes root directory on pod change.
> fix: root directory

- .github/workflows/variables.json
CI configuration is changed so all environments will use `bee-1`.
> ci: bee url fix

- src/components/Buttons/MainSideBarItem/MainSideBarItem.tsx
- src/components/Layouts/MainLayout/MainLayout.tsx
- src/components/NavigationBars/DriveActionBar/DriveActionBarMobile.tsx
- src/components/NavigationBars/MainSideBar/MainSideBar.tsx
On mobile devices, the left sidebar is transformed to a horizontal menu above the drive area.
> feat: sidebar for mobile

- src/components/Modals/UploadFileModal/UploadFileModal.tsx
Upload error moved above the upload button.
> fix: move upload error

- src/components/Cards/EmptyDirectoryCard/EmptyDirectoryCard.tsx
- src/components/DirectoryPath/DirectoryPath.tsx
- src/components/Dropdowns/PodDropdown/PodDropdownToggle.tsx
- src/components/NavigationBars/DriveActionBar/DriveActionBar.tsx
- src/pages/drive/index.tsx
Added back button for showing list of pods.
Closes #482
> feat: add drive back button (#482)

- src/utils/metamask.ts
- test/unit/metamask.test.ts
Close: https://github.com/fairDataSociety/fairdrive-theapp/issues/429
@tfius
> refactor: upgraded text for singing

- package-lock.json
- package.json
> chore: upgrade blossom library

- src/components/Layouts/MainLayout/MainLayout.tsx
Fixed padding at the bottom of main layout.
> fix: layout padding

- src/components/Buttons/MainSideBarItem/MainSideBarItem.tsx
Sidebar button links fixed.
Closes #395
> fix: sidebar #395

- src/api/directory.ts
- src/components/DirectoryPath/DirectoryPath.tsx
- src/components/Dropdowns/PodDropdown/PodDropdownToggle.tsx
- src/components/NavigationBars/DriveActionBar/DriveActionHeaderMobile.tsx
- src/pages/drive/index.tsx
Redesigned how folder path is shown on mobile.
> feat: file path redesign for mobile

- src/components/Dropdowns/PodDropdown/PodDropdownMenu.tsx
- src/components/Dropdowns/PodDropdown/PodDropdownToggle.tsx
- src/locales/ch-CH.json
- src/locales/de-DE.json
- src/locales/en-US.json
- src/locales/es-ES.json
- src/locales/fr-FR.json
- src/locales/hu-HU.json
- src/locales/it-IT.json
- src/locales/jp-JP.json
- src/locales/pt-PT.json
- src/locales/rs-RS.json
- src/locales/sl-SI.json
- src/locales/tr-TR.json
Pod dropdown doesn't open root directory anymore. A new option is added to the pod menu instead.
Closes #502
> fix: pod dropdown (#502)

- src/components/NavigationBars/MobileNavigationDrawer/MobileNavigationDrawer.tsx
> fix: lint error

- src/components/NavigationBars/AuthenticationNavbar/AuthenticationNavbar.tsx
> feat: import button removed

- src/components/NavigationBars/DriveActionBar/DriveActionBarMobile.tsx
- src/locales/ch-CH.json
- src/locales/de-DE.json
- src/locales/en-US.json
- src/locales/es-ES.json
- src/locales/fr-FR.json
- src/locales/hu-HU.json
- src/locales/it-IT.json
- src/locales/jp-JP.json
- src/locales/pt-PT.json
- src/locales/rs-RS.json
- src/locales/sl-SI.json
- src/locales/tr-TR.json
The label "Folder" changed to "New Folder" in the drive menu.
> fix: folder label

- src/components/Buttons/MainSideBarItem/MainSideBarItem.tsx
- src/components/Dropdowns/PodDropdown/PodDropdownMenu.tsx
- src/components/Invite/Invite.tsx
- src/components/Invites/Invites.tsx
- src/components/NavigationBars/MainNavigationBar/MainNavigationBar.tsx
- src/components/NavigationBars/MainNavigationBar/UserDropdown/UserDropdown.tsx
- src/components/NavigationBars/MainSideBar/MainSideBar.tsx
- src/components/NavigationBars/MobileNavigationDrawer/MobileNavigationDrawer.tsx
- Removed the searchbar
- Added scroll to the pod dropdown
- Mobile layout applied to tablet screen size
- Set invite buttons to be visible without hovering
- Fixed the confetti component scroll
- Added padding between username and buttons in the user menu
> feat: various ui improvements

- src/components/Invite/Invite.tsx
Close: https://github.com/fairDataSociety/fairdrive-theapp/issues/387
> fix: upgraded mobile UI for invite section

- src/components/Dialogs/MetamaskMigrationDialog/MetamaskCreateAccount.tsx
- src/utils/error.ts
Fixes error messages in account migration modal.
> fix: error message (#517)

- src/pages/drive/index.tsx
Fixes the dancing elements issue in drive.
> fix: spinner margin (#322)

- src/components/Dropdowns/PodDropdown/PodDropdownToggle.tsx
- src/components/NavigationBars/DriveSideBar/DriveSideBar.tsx
- src/context/PodContext.tsx
- src/pages/drive/index.tsx
Pod change is disabled while drive content is being loaded.
Closes #538
> fix: wrong pod content (#538)

- src/components/FilePreview/FilePreview.tsx
Fixes text color for file preview.
> fix: file preview text

- src/components/Forms/LoginForm/LoginForm.tsx
- src/locales/de-DE.json
- src/locales/en-US.json
- src/locales/es-ES.json
- src/locales/fr-FR.json
- src/locales/hu-HU.json
- src/locales/it-IT.json
- src/locales/jp-JP.json
- src/locales/pt-PT.json
- src/locales/rs-RS.json
- src/locales/sl-SI.json
- src/locales/tr-TR.json
Close: https://github.com/fairDataSociety/fairdrive-theapp/issues/20
> feat: add testnet disclaimer to login form in multiple languages

- src/pages/drive/index.tsx
Fixes error handling.
Closes #551
> fix: error handling (#551)

- src/components/NavigationBars/MainNavigationBar/MainNavigationBar.tsx
- src/pages/drive/index.tsx
Changes appearing of searchbar when it becomes active.
Closes #549
> fix: searchbar appearing (#549)

- Dockerfile
Seems that the app can't build with the latest node docker image.
> ci: older node image

- src/components/Forms/LoginForm/LoginForm.tsx
Fixes redirection page after login.
> fix: login redirection

- src/locales/de-DE.json
- src/locales/en-US.json
- src/locales/es-ES.json
- src/locales/fr-FR.json
- src/locales/hu-HU.json
- src/locales/it-IT.json
- src/locales/ja-JP.json
- src/locales/pt-PT.json
- src/locales/sl-SI.json
- src/locales/sr-LATN.json
- src/locales/tr-TR.json
- src/locales/zh.json
> fix: missing label
